### ISSUE TITLE
Duplicate set of question

### ISSUE THREAD

**Issue by lepiaf** [ProPheT777/certificationy-data#15]
Hi,

The first time I use certificationy, it was with CLI application. 

I realized that your project and CLI project are two different. https://github.com/certificationy/certificationy-cli use a different set of question (https://github.com/certificationy/symfony-pack).

Is there any way to "merge" or "synchronise" data from this repository to certificationy/symfony-pack ?

Thierry

**Comment by ProPheT777** [comment]
Yes, by the hand,, but I have no times to do that :(

**Comment by lepiaf** [comment]
Ok. Thank you.
