### ISSUE TITLE
[Symfony2][Forms] extending TextType

### ISSUE THREAD

**Issue by mheki** [ProPheT777/certificationy-data#21]
Sorry for nagging :smile: . I don't understand this question / answers:
https://github.com/ProPheT777/certificationy-data/blob/master/symfony2/yaml/forms.yml#L79-L83
All of these types extend `AbstractType` tbh. Did you mean: 
`Which of these fields are text fields?` (http://symfony.com/doc/2.3/book/forms.html#text-fields)
What is more `currency` lives under `Choice fields` in the documentation: http://symfony.com/doc/2.3/book/forms.html#choice-fields
Am I missing something?

**Comment by ProPheT777** [comment]
> Am I missing something?

Yes, form type are composite, the extend via `extend` is just here to easily create formType. The real extend is done via `getParent()` method.

You can create a form type from scratch by using `FormTypeInterface` and inherit from `field` type if you want.

Here a diagram of form inheritance : 

![types](https://cloud.githubusercontent.com/assets/1763341/9208058/a6d70908-4071-11e5-9ec5-ee0d2f999a27.png)


and the full article by the form component author : http://webmozarts.com/2012/03/06/symfony2-form-architecture/

**Comment by mheki** [comment]
cheers :+1:
